/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLyPhong;
import HoaDon.HoaDonJF;
import KhachHang.KhachHang;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JTextPane;
import KhachHang.KhachHangJFrame;
import java.awt.event.WindowEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.prefs.Preferences;


import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author User
 */
public class QuanLyPhongJFrame extends javax.swing.JFrame {

     private Color originalBackground;
    private Color originalForeground;
    private String originalText;
    private Icon origiIcon;
     private boolean isClicked;
    private int clickCount;
    private int click101,click102,click103,click201,click202,click203,click301,click302,click303;
    
    
    /**
     * Creates new form QuanLyPhongJFrame
     */
    KhachHangJFrame a;
    public QuanLyPhongJFrame() {
        initComponents();
      setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Đặt phương thức đóng form của template
//        setLayout(new FlowLayout());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btn103 = new javax.swing.JButton();
        btn101 = new javax.swing.JButton();
        btn201 = new javax.swing.JButton();
        btn301 = new javax.swing.JButton();
        btn203 = new javax.swing.JButton();
        btn102 = new javax.swing.JButton();
        btn202 = new javax.swing.JButton();
        btn303 = new javax.swing.JButton();
        btn302 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                jPanel1AncestorResized(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Bed-clock.48.png"))); // NOI18N
        jButton2.setText("Phòng Có Khách");
        jButton2.setToolTipText("");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerifyInputWhenFocusTarget(false);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gartoon-Team-Gartoon-Action-Edit-clear-broom.48.png"))); // NOI18N
        jButton3.setText("Đang Xử Lý ");
        jButton3.setToolTipText("");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerifyInputWhenFocusTarget(false);
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Trạng Thái Phòng");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "<$$$> Quản Lý Phòng <$$$>", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 3, 30), new java.awt.Color(255, 0, 0))); // NOI18N

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icons8-Windows-8-City-Hotel.48.png"))); // NOI18N
        jButton1.setText("Tầng 1");
        jButton1.setToolTipText("");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerifyInputWhenFocusTarget(false);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icons8-Windows-8-City-Hotel.48.png"))); // NOI18N
        jButton7.setText("Tầng 2");
        jButton7.setToolTipText("");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerifyInputWhenFocusTarget(false);
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icons8-Windows-8-City-Hotel.48.png"))); // NOI18N
        jButton8.setText("Tầng 3");
        jButton8.setToolTipText("");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerifyInputWhenFocusTarget(false);
        jButton8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btn103.setBackground(new java.awt.Color(102, 255, 51));
        btn103.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ionic-Ionicons-Bed.48.png"))); // NOI18N
        btn103.setText("Phòng 103");
        btn103.setToolTipText("");
        btn103.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn103.setVerifyInputWhenFocusTarget(false);
        btn103.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn103.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn103ActionPerformed(evt);
            }
        });

        btn101.setBackground(new java.awt.Color(102, 255, 51));
        btn101.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ionic-Ionicons-Bed.48.png"))); // NOI18N
        btn101.setText("Phòng 101");
        btn101.setToolTipText("");
        btn101.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn101.setVerifyInputWhenFocusTarget(false);
        btn101.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn101.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn101ActionPerformed(evt);
            }
        });

        btn201.setBackground(new java.awt.Color(102, 255, 51));
        btn201.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn201.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ionic-Ionicons-Bed.48.png"))); // NOI18N
        btn201.setText("Phòng 201");
        btn201.setToolTipText("");
        btn201.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn201.setVerifyInputWhenFocusTarget(false);
        btn201.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn201.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn201ActionPerformed(evt);
            }
        });

        btn301.setBackground(new java.awt.Color(102, 255, 51));
        btn301.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn301.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ionic-Ionicons-Bed.48.png"))); // NOI18N
        btn301.setText("Phòng 301");
        btn301.setToolTipText("");
        btn301.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn301.setVerifyInputWhenFocusTarget(false);
        btn301.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn301.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn301.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn301ActionPerformed(evt);
            }
        });

        btn203.setBackground(new java.awt.Color(102, 255, 51));
        btn203.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn203.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ionic-Ionicons-Bed.48.png"))); // NOI18N
        btn203.setText("Phòng 203");
        btn203.setToolTipText("");
        btn203.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn203.setVerifyInputWhenFocusTarget(false);
        btn203.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn203.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn203.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn203ActionPerformed(evt);
            }
        });

        btn102.setBackground(new java.awt.Color(102, 255, 51));
        btn102.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ionic-Ionicons-Bed.48.png"))); // NOI18N
        btn102.setText("Phòng 102");
        btn102.setToolTipText("");
        btn102.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn102.setVerifyInputWhenFocusTarget(false);
        btn102.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn102.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn102ActionPerformed(evt);
            }
        });

        btn202.setBackground(new java.awt.Color(102, 255, 51));
        btn202.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn202.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ionic-Ionicons-Bed.48.png"))); // NOI18N
        btn202.setText("Phòng 202");
        btn202.setToolTipText("");
        btn202.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn202.setVerifyInputWhenFocusTarget(false);
        btn202.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn202.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn202ActionPerformed(evt);
            }
        });

        btn303.setBackground(new java.awt.Color(102, 255, 51));
        btn303.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn303.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ionic-Ionicons-Bed.48.png"))); // NOI18N
        btn303.setText("Phòng 303");
        btn303.setToolTipText("");
        btn303.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn303.setVerifyInputWhenFocusTarget(false);
        btn303.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn303.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn303.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn303ActionPerformed(evt);
            }
        });

        btn302.setBackground(new java.awt.Color(102, 255, 51));
        btn302.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn302.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ionic-Ionicons-Bed.48.png"))); // NOI18N
        btn302.setText("Phòng 302");
        btn302.setToolTipText("");
        btn302.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn302.setVerifyInputWhenFocusTarget(false);
        btn302.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn302.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn302.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn302ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn201, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn301, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn101, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn302, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn102, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn202, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn103, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn303, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn203, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn102, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn103, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn201, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn202, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn203, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn302, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn301, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn303, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jButton4.setBackground(new java.awt.Color(102, 255, 51));
        jButton4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ionic-Ionicons-Bed.48.png"))); // NOI18N
        jButton4.setText("Phòng Trống");
        jButton4.setToolTipText("");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerifyInputWhenFocusTarget(false);
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 220, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn302ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn302ActionPerformed
        // TODO add your handling code here:
          if (click302 == 0) {
        originalBackground = btn302.getBackground();
        originalForeground = btn302.getForeground();
        origiIcon = btn302.getIcon();
        //originalText = btn101.getText();

    }

    click302++;
    
    if (click302 == 1) {
        // Thay đổi màu và thông tin lần thứ nhất
        
        a= new KhachHangJFrame();
        a.setVisible(true);
        btn302.setText("Đặt Phòng ");
        btn302.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icojam-Blue-Bits-Picture-check.64.png"))); 
      

    } else if (click302 == 2) {
        // Thay đổi màu và thông tin lần thứ hai
       
        btn302.setBackground(new java.awt.Color(255, 0, 0));
        btn302.setForeground(Color.BLACK);
        btn302.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Bed-clock.48.png")));
        btn302.setText("Mã KH: "+ a.getMaKHText());
        
        queryDaDat(302);


    }else if(click302 == 3){
        int option = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xác nhận Trả Phòng không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
       
        if(option == JOptionPane.YES_OPTION){
            queryTrong(302);
             btn302.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gartoon-Team-Gartoon-Action-Edit-clear-broom.48.png")));
        btn302.setBackground(new java.awt.Color(0, 204, 204));
        btn302.setForeground(Color.BLACK);
        btn302.setText( "Đang Xử Lý");
        HoaDonJF a = new HoaDonJF();
        a.setVisible(true);
        }else if(option == JOptionPane.NO_OPTION ){
        click302--;
    }
        
    //} else if (clickCount == 4) {
       

        
    }else if (click302 == 4) {
        // Quay trở lại màu và thông tin gốc
        btn302.setBackground(originalBackground);
        btn302.setForeground(originalForeground);
        btn302.setText("Phòng 302");   
        btn302.setIcon(origiIcon);
        click302= 0;
    }
    }//GEN-LAST:event_btn302ActionPerformed

    private void btn303ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn303ActionPerformed
        // TODO add your handling code here:
            if (click303 == 0) {
        originalBackground = btn303.getBackground();
        originalForeground = btn303.getForeground();
        origiIcon = btn303.getIcon();
        //originalText = btn101.getText();

    }

    click303++;
    
    if (click303 == 1) {
        // Thay đổi màu và thông tin lần thứ nhất
        
        a= new KhachHangJFrame();
        a.setVisible(true);
        btn303.setText("Đặt Phòng ");
        btn303.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icojam-Blue-Bits-Picture-check.64.png"))); 
      

    } else if (click303 == 2) {
        // Thay đổi màu và thông tin lần thứ hai
       
        btn303.setBackground(new java.awt.Color(255, 0, 0));
        btn303.setForeground(Color.BLACK);
        btn303.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Bed-clock.48.png")));
        btn303.setText("Mã KH: "+ a.getMaKHText());
        
        queryDaDat(303);


    }else if(click303 == 3){
        int option = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xác nhận Trả Phòng không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
       
        if(option == JOptionPane.YES_OPTION){
            queryTrong(303);
             btn303.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gartoon-Team-Gartoon-Action-Edit-clear-broom.48.png")));
        btn303.setBackground(new java.awt.Color(0, 204, 204));
        btn303.setForeground(Color.BLACK);
        btn303.setText( "Đang Xử Lý");
        HoaDonJF a = new HoaDonJF();
        a.setVisible(true);
        }else if(option == JOptionPane.NO_OPTION ){
        click303--;
    }
        
    //} else if (clickCount == 4) {
       

        
    }else if (click303 == 4) {
        // Quay trở lại màu và thông tin gốc
        btn303.setBackground(originalBackground);
       btn303.setForeground(originalForeground);
        btn303.setText("Phòng 303");   
        btn303.setIcon(origiIcon);
        click303 = 0;
    }
    }//GEN-LAST:event_btn303ActionPerformed

    private void btn202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn202ActionPerformed
         if (click202 == 0) {
        originalBackground = btn202.getBackground();
        originalForeground = btn202.getForeground();
        origiIcon = btn202.getIcon();
        //originalText = btn101.getText();

    }

    click202++;
    
    if (click202 == 1) {
        // Thay đổi màu và thông tin lần thứ nhất
        
        a= new KhachHangJFrame();
        a.setVisible(true);
        btn202.setText("Đặt Phòng ");
        btn202.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icojam-Blue-Bits-Picture-check.64.png"))); 
      

    } else if (click202 == 2) {
        // Thay đổi màu và thông tin lần thứ hai
       
        btn202.setBackground(new java.awt.Color(255, 0, 0));
        btn202.setForeground(Color.BLACK);
        btn202.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Bed-clock.48.png")));
        btn202.setText("Mã KH: "+ a.getMaKHText());
        
        queryDaDat(202);


    }else if(click202 == 3){
        int option = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xác nhận Trả Phòng không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
       
        if(option == JOptionPane.YES_OPTION){
            queryTrong(202);
             btn202.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gartoon-Team-Gartoon-Action-Edit-clear-broom.48.png")));
        btn202.setBackground(new java.awt.Color(0, 204, 204));
        btn202.setForeground(Color.BLACK);
        btn202.setText( "Đang Xử Lý");
        HoaDonJF a = new HoaDonJF();
        a.setVisible(true);
        }else if(option == JOptionPane.NO_OPTION ){
        click202--;
    }
        
    //} else if (clickCount == 4) {
       

        
    }else if (click202 == 4) {
        // Quay trở lại màu và thông tin gốc
        btn202.setBackground(originalBackground);
       btn202.setForeground(originalForeground);
        btn202.setText("Phòng 202");   
        btn202.setIcon(origiIcon);
        click202 = 0;
    }
    }//GEN-LAST:event_btn202ActionPerformed

    private void btn102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn102ActionPerformed
        // TODO add your handling code here:
            if (click102 == 0) {
        originalBackground = btn102.getBackground();
        originalForeground = btn102.getForeground();
        origiIcon = btn102.getIcon();
        originalText = btn102.getText();

    }

    click102++;
    
    if (click102 == 1) {
        // Thay đổi màu và thông tin lần thứ nhất
        
        a= new KhachHangJFrame();
        a.setVisible(true);
        btn102.setText("Đặt Phòng ");
        btn102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icojam-Blue-Bits-Picture-check.64.png"))); 
      

    } else if (click102 == 2) {
        // Thay đổi màu và thông tin lần thứ hai
       
        btn102.setBackground(new java.awt.Color(255, 0, 0));
        btn102.setForeground(Color.BLACK);
        btn102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Bed-clock.48.png")));
        btn102.setText("Mã KH: "+ a.getMaKHText());
        
        queryDaDat(102);


    }else if(click102 == 3){
        int option = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xác nhận Trả Phòng không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
       
        if(option == JOptionPane.YES_OPTION){
            queryTrong(102);
             btn102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gartoon-Team-Gartoon-Action-Edit-clear-broom.48.png")));
        btn102.setBackground(new java.awt.Color(0, 204, 204));
        btn102.setForeground(Color.BLACK);
        btn102.setText( "Đang Xử Lý");
        HoaDonJF a = new HoaDonJF();
        a.setVisible(true);
        }else if(option == JOptionPane.NO_OPTION ){
        click102--;
    }
        
    //} else if (clickCount == 4) {
       

        
    }else if (click102 == 4) {
        // Quay trở lại màu và thông tin gốc
        btn102.setBackground(originalBackground);
       btn102.setForeground(originalForeground);
        btn102.setText("Phòng 102");   
        btn102.setIcon(origiIcon);
        click102 = 0;
    }
    }//GEN-LAST:event_btn102ActionPerformed

    private void btn203ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn203ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // Thay Đổi Nút BTN cho quản lý phòng
         if (click203 == 0) {
        originalBackground = btn203.getBackground();
        originalForeground = btn203.getForeground();
        origiIcon = btn203.getIcon();
        //originalText = btn101.getText();

    }

    click203++;
    
    if (click203 == 1) {
        // Thay đổi màu và thông tin lần thứ nhất
        
        a= new KhachHangJFrame();
        a.setVisible(true);
        btn203.setText("Đặt Phòng ");
        btn203.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icojam-Blue-Bits-Picture-check.64.png"))); 
      

    } else if (click203 == 2) {
        // Thay đổi màu và thông tin lần thứ hai
       
        btn203.setBackground(new java.awt.Color(255, 0, 0));
        btn203.setForeground(Color.BLACK);
        btn203.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Bed-clock.48.png")));
        btn203.setText("Mã KH: "+ a.getMaKHText());
        
        queryDaDat(203);


    }else if(click203 == 3){
        int option = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xác nhận Trả Phòng không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
       
        if(option == JOptionPane.YES_OPTION){
            queryTrong(203);
             btn203.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gartoon-Team-Gartoon-Action-Edit-clear-broom.48.png")));
        btn203.setBackground(new java.awt.Color(0, 204, 204));
        btn203.setForeground(Color.BLACK);
        btn203.setText( "Đang Xử Lý");
        HoaDonJF a = new HoaDonJF();
        a.setVisible(true);
        }else if(option == JOptionPane.NO_OPTION ){
        click203--;
    }
        
    //} else if (clickCount == 4) {
       

        
    }else if (click203 == 4) {
        // Quay trở lại màu và thông tin gốc
        btn203.setBackground(originalBackground);
       btn203.setForeground(originalForeground);
        btn203.setText("Phòng 203");   
        btn203.setIcon(origiIcon);
        click203 = 0;
    }
    }//GEN-LAST:event_btn203ActionPerformed

    private void btn301ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn301ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // Thay Đổi Nút BTN cho quản lý phòng
         if (click301 == 0) {
        originalBackground = btn301.getBackground();
        originalForeground = btn301.getForeground();
        origiIcon = btn301.getIcon();
        //originalText = btn101.getText();

    }

    click301++;
    
    if (click301 == 1) {
        // Thay đổi màu và thông tin lần thứ nhất
        
        a= new KhachHangJFrame();
        a.setVisible(true);
        btn301.setText("Đặt Phòng ");
        btn301.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icojam-Blue-Bits-Picture-check.64.png"))); 
      

    } else if (click301 == 2) {
        // Thay đổi màu và thông tin lần thứ hai
       
        btn301.setBackground(new java.awt.Color(255, 0, 0));
        btn301.setForeground(Color.BLACK);
        btn301.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Bed-clock.48.png")));
        btn301.setText("Mã KH: "+ a.getMaKHText());
        
        queryDaDat(301);


    }else if(click301 == 3){
        int option = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xác nhận Trả Phòng không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
       
        if(option == JOptionPane.YES_OPTION){
            queryTrong(301);
             btn301.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gartoon-Team-Gartoon-Action-Edit-clear-broom.48.png")));
        btn301.setBackground(new java.awt.Color(0, 204, 204));
        btn301.setForeground(Color.BLACK);
        btn301.setText( "Đang Xử Lý");
        HoaDonJF a = new HoaDonJF();
        a.setVisible(true);
        }else if(option == JOptionPane.NO_OPTION ){
        click301--;
    }
        
    //} else if (clickCount == 4) {
       

        
    }else if (click301 == 4) {
        // Quay trở lại màu và thông tin gốc
        btn301.setBackground(originalBackground);
       btn301.setForeground(originalForeground);
        btn301.setText("Phòng 301");   
        btn301.setIcon(origiIcon);
        click301 = 0;
    }
    }//GEN-LAST:event_btn301ActionPerformed

    private void btn201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn201ActionPerformed
             if (click201 == 0) {
        originalBackground = btn201.getBackground();
        originalForeground = btn201.getForeground();
        origiIcon = btn201.getIcon();
        //originalText = btn101.getText();

    }

    click201++;
    
    if (click201 == 1) {
        // Thay đổi màu và thông tin lần thứ nhất
        
        a= new KhachHangJFrame();
        a.setVisible(true);
        btn201.setText("Đặt Phòng ");
        btn201.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icojam-Blue-Bits-Picture-check.64.png"))); 
      

    } else if (click201 == 2) {
        // Thay đổi màu và thông tin lần thứ hai
       
        btn201.setBackground(new java.awt.Color(255, 0, 0));
        btn201.setForeground(Color.BLACK);
        btn201.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Bed-clock.48.png")));
        btn201.setText("Mã KH: "+ a.getMaKHText());
        
        queryDaDat(201);


    }else if(click201 == 3){
        int option = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xác nhận Trả Phòng không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
       
        if(option == JOptionPane.YES_OPTION){
            queryTrong(201);
             btn201.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gartoon-Team-Gartoon-Action-Edit-clear-broom.48.png")));
        btn201.setBackground(new java.awt.Color(0, 204, 204));
        btn201.setForeground(Color.BLACK);
        btn201.setText( "Đang Xử Lý");
        HoaDonJF a = new HoaDonJF();
        a.setVisible(true);
        }else if(option == JOptionPane.NO_OPTION ){
        click201--;
    }
        
    //} else if (clickCount == 4) {
       

        
    }else if (click201 == 4) {
        // Quay trở lại màu và thông tin gốc
        btn201.setBackground(originalBackground);
       btn201.setForeground(originalForeground);
        btn201.setText("Phòng 201");   
        btn201.setIcon(origiIcon);
        click201 = 0;
    }
    }//GEN-LAST:event_btn201ActionPerformed

    private void btn101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn101ActionPerformed
        // TODO add your handling code here:
        
            if (click101 == 0) {
        originalBackground = btn101.getBackground();
        originalForeground = btn101.getForeground();
        origiIcon = btn101.getIcon();
        //originalText = btn101.getText();

    }

    click101++;
    
    if (click101 == 1) {
        // Thay đổi màu và thông tin lần thứ nhất
        
        a= new KhachHangJFrame();
        a.setVisible(true);
        btn101.setText("Đặt Phòng ");
        btn101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icojam-Blue-Bits-Picture-check.64.png"))); 
      

    } else if (click101 == 2) {
        // Thay đổi màu và thông tin lần thứ hai
       
        btn101.setBackground(new java.awt.Color(255, 0, 0));
        btn101.setForeground(Color.BLACK);
        btn101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Bed-clock.48.png")));
        btn101.setText("Mã KH: "+ a.getMaKHText());
        
        queryDaDat(101);


    }else if(click101 == 3){
        int option = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xác nhận Trả Phòng không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
       
        if(option == JOptionPane.YES_OPTION){
            queryTrong(101);
             btn101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gartoon-Team-Gartoon-Action-Edit-clear-broom.48.png")));
        btn101.setBackground(new java.awt.Color(0, 204, 204));
        btn101.setForeground(Color.BLACK);
        btn101.setText( "Đang Xử Lý");
        HoaDonJF a = new HoaDonJF();
        a.setVisible(true);
        }else if(option == JOptionPane.NO_OPTION ){
        click101--;
    }
        
    //} else if (clickCount == 4) {
       

        
    }else if (click101 == 4) {
        // Quay trở lại màu và thông tin gốc
        btn101.setBackground(originalBackground);
       btn101.setForeground(originalForeground);
        btn101.setText("Phòng 101");   
        btn101.setIcon(origiIcon);
        click101 = 0;
    }
    
    
    }//GEN-LAST:event_btn101ActionPerformed
        
 
        
    
    private void btn103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn103ActionPerformed
        // TODO add your handling code here:
        // Thay Đổi Nút BTN cho quản lý phòng
             if (click103 == 0) {
        originalBackground = btn103.getBackground();
        originalForeground = btn103.getForeground();
        origiIcon = btn103.getIcon();
        originalText = btn103.getText();

    }

    click103++;
    
    if (click103 == 1) {
        // Thay đổi màu và thông tin lần thứ nhất
        
        a= new KhachHangJFrame();
        a.setVisible(true);
        btn103.setText("Đặt Phòng ");
        btn103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icojam-Blue-Bits-Picture-check.64.png"))); 
      

    } else if (click103 == 2) {
        // Thay đổi màu và thông tin lần thứ hai
       
        btn103.setBackground(new java.awt.Color(255, 0, 0));
        btn103.setForeground(Color.BLACK);
        btn103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Bed-clock.48.png")));
        btn103.setText("Mã KH: "+ a.getMaKHText());
        
        queryDaDat(103);


    }else if(click103 == 3){
        int option = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xác nhận Trả Phòng không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
       
        if(option == JOptionPane.YES_OPTION){
            queryTrong(103);
             btn103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gartoon-Team-Gartoon-Action-Edit-clear-broom.48.png")));
        btn103.setBackground(new java.awt.Color(0, 204, 204));
        btn103.setForeground(Color.BLACK);
        btn103.setText( "Đang Xử Lý");
        HoaDonJF a = new HoaDonJF();
        a.setVisible(true);
        }else if(option == JOptionPane.NO_OPTION ){
        click103--;
    }
        
    //} else if (clickCount == 4) {
       

        
    }else if (click103 == 4) {
        // Quay trở lại màu và thông tin gốc
        btn103.setBackground(originalBackground);
       btn103.setForeground(originalForeground);
        btn103.setText("Phòng 103");   
        btn103.setIcon(origiIcon);
        click103 = 0;
    }
    }//GEN-LAST:event_btn103ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel1AncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel1AncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1AncestorResized

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Hàm nút đặt phòng
    public void queryTrong(int ma){
         String sql ="Update Phong set trangthai = 'Trống' where maphong = ?";
            QuanLyPhongController a =  new QuanLyPhongController();
            try (Connection conn = a.getConnection();
                 PreparedStatement stmt = conn.prepareStatement(sql)){
                
                stmt.setInt(1, ma);

            }catch(SQLException e){
                e.printStackTrace();
            }
    }
    public void queryDaDat(int ma){
         String sql ="Update Phong set trangthai = 'Đã đặt' where maphong = ?";
            QuanLyPhongController a =  new QuanLyPhongController();
            try (Connection conn = a.getConnection();
                 PreparedStatement stmt = conn.prepareStatement(sql)){
                stmt.setInt(1, ma);
                stmt.executeUpdate();

            }catch(SQLException e){
                e.printStackTrace();
            }
    }


   // int clickCount = 0;
//    public void updatebtnPhong(JButton btn,int clickCount){
//        // TODO add your handling code here:
//        // Thay Đổi Nút BTN cho quản lý phòng
//      
// 
//            if ( clickCount == 0) {
//        originalBackground = btn.getBackground();
//        originalForeground = btn.getForeground();
//        origiIcon = btn.getIcon();
//        originalText = btn.getText();
//
//    }
//
//    clickCount++;
//    
//    if (clickCount == 1) {
//        // Thay đổi màu và thông tin lần thứ nhất
//        
//        a= new KhachHangJFrame();
//        a.setVisible(true);
//        btn.setText("Đặt Phòng ");
//        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icojam-Blue-Bits-Picture-check.64.png"))); 
//      
//
//    } else if (clickCount == 2) {
//        // Thay đổi màu và thông tin lần thứ hai
//       
//        btn.setBackground(new java.awt.Color(255, 0, 0));
//        btn.setForeground(Color.BLACK);
//        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pictogrammers-Material-Bed-clock.48.png")));
//        btn.setText("Mã KH: "+ a.getMaKHText());
//        
//        queryDaDat(ma);
//
//
//    }else if(clickCount == 3){
//        int option = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xác nhận Trả Phòng không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
//       
//        if(option == JOptionPane.YES_OPTION){
//            queryTrong(ma);
//             btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Gartoon-Team-Gartoon-Action-Edit-clear-broom.48.png")));
//        btn.setBackground(new java.awt.Color(0, 204, 204));
//        btn.setForeground(Color.BLACK);
//        btn.setText( "Đang Xử Lý");
//        }else if(option == JOptionPane.NO_OPTION ){
//        clickCount--;
//    }
//        
//    //} else if (clickCount == 4) {
//       
//
//        
//    }else if (clickCount == 4) {
//        // Quay trở lại màu và thông tin gốc
//        btn.setBackground(originalBackground);
//       btn.setForeground(originalForeground);
//        btn.setText(originalText);   
//        btn.setIcon(origiIcon);
//        clickCount = 0;
//    }

//    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhongJFrame().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn101;
    private javax.swing.JButton btn102;
    private javax.swing.JButton btn103;
    private javax.swing.JButton btn201;
    private javax.swing.JButton btn202;
    private javax.swing.JButton btn203;
    private javax.swing.JButton btn301;
    private javax.swing.JButton btn302;
    private javax.swing.JButton btn303;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
